<?php

namespace ContactsBundle\Repository;

/**
 * ContactsGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactsGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
